### ISSUE TITLE
Unable to read schema document

### ISSUE THREAD

**Issue by steghio** [occi4java/libvirt4occi#3]
Greetings,

I'm using libvirt4occi on Ubuntu 11.10. I installed it via software center and I installed the qemu-kvm and libvirt-bin dependencies via terminal. I started it with sudo /etc/init.d/libvirt4occi start. I'm working behind a proxy which requires authentication.

I can start it properly with no errors. netstat -a | grep 8182 shows someone is listening on that port but then, when I send a sample request (Query Interface->GET) from the Chrome "Simple OCCI client" extension, I get 500 internal server error:

HTTP/1.1 500 Internal Server Error
Date: Fri, 28 Oct 2011 08:34:23 GMT
Via: 1.0 proxy.EDIT (squid/2.6.STABLE5)
X-Cache-Lookup: HIT from proxy.EDIT
X-Cache: MISS from proxy.EDIT
Proxy-Connection: close
Content-Length: 486
Server: OCCI/1.1
Vary: Accept-Charset, Accept-Encoding, Accept-Language, Accept
Content-Type: text/html; charset=UTF-8

netstat shows that there's a connection established on 8182

The logfile reports Failed to read schema document 'http://www.springframework.org/schema/beans/spring-beans-3.0.xsd', which is reachable, readable and well formed:

2011-10-28 10:40:39,822 DEBUG [Dispatcher-0] occi.http.OcciRestQuery: getReference().getLastSegment(): -
2011-10-28 10:40:39,831 INFO  [Dispatcher-0] org.springframework.beans.factory.xml.XmlBeanDefinitionReader: Loading XML bean definitions from class path resource [occiConfig.xml]
2011-10-28 10:40:39,876 WARN  [Dispatcher-0] org.springframework.beans.factory.xml.XmlBeanDefinitionReader: Ignored XML validation warning
org.xml.sax.SAXParseException; lineNumber: 25; columnNumber: 132; schema_reference.4: Failed to read schema document 'http://www.springframework.org/schema/beans/spring-beans-3.0.xsd', because 1) could not find the document; 2) the document could not be read; 3) the root element of the document is not xsd:schema.
    at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:198)
    at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.warning(ErrorHandlerWrapper.java:99)
    at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:383)
    at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:321)
    at com.sun.org.apache.xerces.internal.impl.xs.traversers.XSDHandler.reportSchemaErr(XSDHandler.java:2562)
    at com.sun.org.apache.xerces.internal.impl.xs.traversers.XSDHandler.reportSchemaWarning(XSDHandler.java:2553)
    at com.sun.org.apache.xerces.internal.impl.xs.traversers.XSDHandler.getSchemaDocument(XSDHandler.java:1849)
    at com.sun.org.apache.xerces.internal.impl.xs.traversers.XSDHandler.parseSchema(XSDHandler.java:540)
    at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaLoader.loadSchema(XMLSchemaLoader.java:564)
    at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaValidator.findSchemaGrammar(XMLSchemaValidator.java:2441)
    at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaValidator.handleStartElement(XMLSchemaValidator.java:1786)
    at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaValidator.startElement(XMLSchemaValidator.java:709)
    at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.scanStartElement(XMLNSDocumentScannerImpl.java:376)
    at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl$NSContentDriver.scanRootElementHook(XMLNSDocumentScannerImpl.java:602)
    at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:3080)
    at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl$PrologDriver.next(XMLDocumentScannerImpl.java:899)
    at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:625)
    at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:116)
    at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:488)
    at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:819)
    at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:748)
    at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:123)
    at com.sun.org.apache.xerces.internal.parsers.DOMParser.parse(DOMParser.java:239)
    at com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:288)
    at org.springframework.beans.factory.xml.DefaultDocumentLoader.loadDocument(DefaultDocumentLoader.java:75)
    at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.doLoadBeanDefinitions(XmlBeanDefinitionReader.java:396)
    at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.loadBeanDefinitions(XmlBeanDefinitionReader.java:342)
    at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.loadBeanDefinitions(XmlBeanDefinitionReader.java:310)
    at org.springframework.beans.factory.xml.XmlBeanFactory.<init>(XmlBeanFactory.java:73)
    at org.springframework.beans.factory.xml.XmlBeanFactory.<init>(XmlBeanFactory.java:61)
    at occi.infrastructure.Compute.<clinit>(Compute.java:111)
    at occi.http.OcciRestQuery.createQueryKinds(OcciRestQuery.java:403)
    at occi.http.OcciRestQuery.getOCCIRequest(OcciRestQuery.java:88)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:616)
    at org.restlet.resource.ServerResource.doHandle(ServerResource.java:449)
    at org.restlet.resource.ServerResource.get(ServerResource.java:645)
    at org.restlet.resource.ServerResource.doHandle(ServerResource.java:527)
    at org.restlet.resource.ServerResource.doNegotiatedHandle(ServerResource.java:587)
    at org.restlet.resource.ServerResource.doConditionalHandle(ServerResource.java:299)
    at org.restlet.resource.ServerResource.handle(ServerResource.java:846)
    at org.restlet.resource.Finder.handle(Finder.java:510)
    at org.restlet.routing.Filter.doHandle(Filter.java:156)
    at org.restlet.routing.Filter.handle(Filter.java:203)
    at org.restlet.routing.Router.doHandle(Router.java:497)
    at org.restlet.routing.Router.handle(Router.java:737)
    at org.restlet.routing.Filter.doHandle(Filter.java:156)
    at org.restlet.routing.Filter.handle(Filter.java:203)
    at org.restlet.routing.Router.doHandle(Router.java:497)
    at org.restlet.routing.Router.handle(Router.java:737)
    at org.restlet.routing.Filter.doHandle(Filter.java:156)
    at org.restlet.engine.application.StatusFilter.doHandle(StatusFilter.java:151)
    at org.restlet.routing.Filter.handle(Filter.java:203)
    at org.restlet.routing.Filter.doHandle(Filter.java:156)
    at org.restlet.routing.Filter.handle(Filter.java:203)
    at org.restlet.engine.ChainHelper.handle(ChainHelper.java:111)
    at org.restlet.Component.handle(Component.java:387)
    at org.restlet.Server.handle(Server.java:488)
    at org.restlet.engine.ServerHelper.handle(ServerHelper.java:71)
    at org.restlet.engine.http.HttpServerHelper.handle(HttpServerHelper.java:150)
    at org.restlet.ext.simple.internal.SimpleContainer.handle(SimpleContainer.java:77)
    at org.simpleframework.http.core.Dispatcher.dispatch(Dispatcher.java:107)
    at org.simpleframework.http.core.Dispatcher.run(Dispatcher.java:90)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
    at java.lang.Thread.run(Thread.java:679)

That exception occurs when I try any of the three example operations.

I think I'm missing something here, could you help?

Thank you,

cheers

**Comment by lxndrp** [comment]
I guess Spring is not properly installed; I cc:ed the developers -- they might be able to help you out.

-Alexander

Am 28.10.2011 um 10:47 schrieb steghio:

**Comment by steghio** [comment]
Cheers,

thank you for your reply. Why would I have to install Spring? I'm using the compiled and bundled version I downloaded here on Github, I didn't compile it from source.

Plus, it always happens when trying to read that particular file but changing the beans.xml in /usr/share/libvirt4occi/conf to make it read the 3.1 file didn't work.

I guess it's because Compute.java under occi4java\infrastructure\src\main\java\occi\infrastructure at line 111 has:

private static XmlBeanFactory beanFactory = new XmlBeanFactory(new ClassPathResource("occiConfig.xml"));

which always tries to read occi4java\infrastructure\src\main\resources\occiConfig.xml which has this line inside:

<beans xmlns="http://www.springframework.org/schema/beans"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:aop="http://www.springframework.org/schema/aop"
    xsi:schemaLocation="http://www.springframework.org/schema/beans http://www.springframework.org/schema/beans/spring-beans-3.0.xsd">

which refers statically to 3.0 version
